config/routes.rb
Rails.application.routes.draw do
  
  resources :bids
  root 'welcome#index'
  get 'welcome/index'
  
  resources :auctions do
    resources :bids, only: [:create, :destroy]
  end
  
  resources :users, only: [:new, :create]

  resources :sessions, only: [:new, :create] do
    delete :destroy, on: :collection
  end
  
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    user ||= User.new
    
    can :manage, Auction do |auction|
      auction.user == user
    end

    can :manage, Bid do |bid|
      bid.auction.user != user
    end
  end
end

app/models/auction.rb
class Auction < ActiveRecord::Base
  
  belongs_to :user
  has_many :bids, dependent: :nullify
  after_initialize :default_values

  validates :title, presence: true
  validates :description, presence: true
  validates :ends_on, presence: true, ends_on: true
  validates :reserve_price, numericality: { greater_than_or_equal_to: 0, only_integer: true}

  scope :most_recent, lambda { |x| order("created_at DESC").limit(x) }

  private
  
  def default_values
    if self.reserve_price == nil
      self.current_price ||= 0
    elsif  self.reserve_price > 0
      self.current_price ||= 0
    else
      self.current_price ||= 0
    end
  end
end

app/models/bid.rb
class Bid < ActiveRecord::Base
  belongs_to :user
  belongs_to :auction

  validates :amount, numericality: {greater_than_or_equal_to: 0}, bid: true
end

app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password

  has_many :auctions, dependent: :nullify
  has_many :bids, dependent: :nullify

  validates :first_name, presence: true
  validates :email, presence: true, uniqueness: true, email: true
  validates :password, length: { in: 6..20 }

  def full_name
    "#{first_name} #{last_name}".strip
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  def authenticate_user!
    redirect_to new_session_path, alert: "Please sign in." unless session[:user_id].present?
  end

  def current_user
    @current_user ||= User.find_by_id session[:user_id]
  end
  helper_method :current_user

  def user_signed_in?
    current_user.present?
  end
  helper_method :user_signed_in?

  # def user_auctions
  #   if user_signed_in?
      
  #   else

  #   end
  # end

end

app/controllers/auctions_controller.rb
class AuctionsController < ApplicationController
  before_action :authenticate_user!, only: [:new, :create, :edit, :update, :destroy]

  def index
    @auctions = Auction.all
  end

  def new
    @auction = Auction.new
  end

  def create
    @auction = Auction.new auction_params
    @auction.user = current_user
    if @auction.save
      flash[:notice] = "Awesome! Your auction has been created!"
      redirect_to auction_path(@auction)
    else
      flash[:alert] = "Oops! Something went wrong. Auction not created."
      render :new
    end
  end

  def show
    @auction = Auction.find params[:id]
  end

  def edit
    @auction = current_user.auctions.find params[:id]
  end

  def update
    @auction = current_user.auctions.find params[:id]
    if @auction.update auction_params
      redirect_to @auction, notice: "Sweet! The auction has been updated."
    else
      flash[:alert] = "Uh-oh... the auction was not updated."
      render :edit
    end
  end

  def destroy
    @auction = current_user.auctions.find params[:id]
    @auction.destroy
    redirect_to auctions_path, notice: "Ka-boom! Auction destroyed."
  end
  
  private

  def auction_params 
    params.require(:auction).permit(:title, :description, :reserve_price, :ends_on, :current_price)
  end

end

app/controllers/bids_controller.rb
class BidsController < ApplicationController
  before_action :authenticate_user!

  def create
    @auction        = Auction.find params[:auction_id]
    @bid            = Bid.new bid_params
    @bid.user       = current_user
    @bid.auction    = @auction
    if @bid.save
      @auction.update_attributes(current_price: @bid.amount)
      redirect_to @auction, notice: "Bid created"
    else
      flash[:alert] = "Bid not created"
      render "auctions/show"
    end
  end

  def destroy
    @auction = Auction.find params[:auction_id]
    @bid   = current_user.bids.find params[:id]
    @bid.destroy
    redirect_to @auction, notice: "Bid destroyed"
  end

  private

  def bid_params
    params.require(:bid).permit(:amount)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
  end

  def create
    @user = User.find_by_email params[:email]
    if @user && @user.authenticate(params[:password])
      session[:user_id] = @user.id
      redirect_to root_path, notice: "Logged in! Welcome."
    else
      flash[:alert] = "You did not provide the correct credentials."
      render :new
    end
  end

  def destroy
    session[:user_id] = nil
    flash[:notice] = "Logged out! See you soon."
    redirect_to root_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  
  def new
    @user = User.new
  end

  def create
    @user = User.new user_params
    if @user.save
      flash[:notice] = "Account created!"
      redirect_to root_path
    else
      flash[:alert] = "Account was not created!"
      render :new
    end 
  end

  private

  def user_params
    params.require(:user).permit( :first_name, 
                                  :last_name, 
                                  :email,
                                  :password, 
                                  :password_confirmation)
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
    @auctions = Auction.most_recent(5)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/auctions_helper.rb
module AuctionsHelper
end

app/helpers/bids_helper.rb
module BidsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/auctions/_form.html.erb
<%= simple_form_for @auction do |f| %>
  <%= f.input :title, required: false, placeholder: "e.g. 'My awesome time machine'"%>
  <%= f.input :description, required: false, placeholder: "e.g. 'It sends you back in time similar to doctor who's phone booth" %>
  <%= f.input :ends_on %>
  <%= f.input :reserve_price, inline_label: "$" %>
  <%= f.submit "Create Auction", class: "btn btn-primary"%>
<% end %>

app/views/auctions/index.html.erb
<h1>All Auctions</h1>
<table class="table table-striped">
  <thead>
    <tr>
      <th>Auction id</th>
      <th>Title</th>
      <th>Description</th>
      <th>Current Price</th>
      <th>Reserve Price</th>
      <th>Ends On</th>
    </tr>
  </thead>
  <tbody>
    <% @auctions.each do |auction| %>
      <tr>
        <td><%= link_to auction.id, auction %></td>
        <td><%= link_to auction.title, auction %></td>
        <td><%= link_to auction.description.truncate(140), auction%></td>
        <td>$<%= auction.current_price %></td>
        <td>$<%= auction.reserve_price %></td>
        <td><%= auction.ends_on %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/auctions/new.html.erb
<div class="container">
  <h1>Create a new auction</h1>
  <div class="row">
    <div class="col-md-6">
      <%= render "form" %>
    </div>
  </div>
</div>

app/views/auctions/show.html.erb
<h1><%= @auction.title %></h1>
<p><%= @auction.description %></p>
<p>Current Price: <%= number_to_currency(@auction.current_price) %></p>
<p>Reserve Price: <%= number_to_currency(@auction.reserve_price) %></p>
<p>Ends On: <%= @auction.ends_on.strftime("%Y-%b-%d") %></p>
<% if can? :edit, @auction %>
  <%= link_to "Edit", edit_auction_path(@auction), class: "btn btn-info" %>
<% end %>
<% if can? :destroy, @auction %>
  <%= link_to "Delete", @auction, class: "btn btn-danger", method: :delete, data: {confirm: "Are you sure?"} %>
<% end %>

app/views/layouts/_navbar.html.erb
<div class="navbar navbar-inverse navbar-fixed-top">
  <div class="navbar-inner">
    <div class="container">
      <%= link_to "Biddr", root_path, class: "navbar-brand" %>
      <ul class="nav navbar-nav navbar-left">
      <li><a href="<%= auctions_path %>">All Auctions</a>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <li><a href="<%= new_auction_path %>"><span class="glyphicon glyphicon-plus"></span> Create Auction</a></li>
        <% if user_signed_in? %>
          <li><a href="<%= root_path %>"><span class="glyphicon glyphicon-user"></span> <%= current_user.full_name %></a></li>
          <li>
            <%= link_to '<span class="glyphicon glyphicon-log-out"></span> Logout'.html_safe, sessions_path, method: :delete %>
          </li>
        <% else %>
          <li><a href="<%= new_user_path %>"><span class="glyphicon glyphicon-user"></span> Sign Up</a></li>
          <li><a href="<%= new_session_path %>"><span class="glyphicon glyphicon-log-in"></span> Login</a></li>
        <% end %>
      </ul>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Biddr - better than ebay</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>

<body>
<%= render "/layouts/navbar" %>
<div class="container">  
  <% if flash[:notice] %>
    <div class="alert alert-success"><%= flash[:notice] %></div>
  <% elsif flash[:alert] %>
    <div class="alert alert-danger"><%= flash[:alert] %></div>
  <% end %>
  
  <%= yield %>
</div>
</body>
</html>

app/views/users/new.html.erb
<div class="container">
  <h1>New to Biddr? Sign up</h1>
</div>

<div class="container">
  <div class="row">
    <div class="col-md-4">
      <%= simple_form_for @user do |f| %>
        <%= f.input :first_name, required: false, placeholder: 'Jane'%>
        <%= f.input :last_name, placeholder: 'Doe' %>
        <%= f.input :email, required: false, placeholder: 'your@email.com' %>
        <%= f.input :password, placeholder: 'between 6 and 20 characters' %>
        <%= f.input :password_confirmation, placeholder: 'same as above' %>
        <%= f.submit "Create Account", class: 'btn btn-primary' %>
      <% end %>
    </div>
    <div class="col-md-8"></div>
  </div>
</div>

app/views/welcome/index.html.erb
<div class="container">
  <div class="col-md-8">
    <div class="row">
      <h1>Biddr</h1>
      <p>It's better than eBay</p>
      <hr>
      <h2>Newest Auctions</h2>
      <p>The current price is in paranthesis after the auction name.</p>
      <% @auctions.each do |auction| %>
        <h4><%= link_to auction.title, auction %> ($<%= auction.current_price %>)</h4>
        <p><%= auction.description %></p>
      <% end %>
    </div>
  </div>
</div>